atmosic:ATM33xx-5:drivers:dma::
Atmosic/hal_atmosic pull request #3
Opened 2024-09-18 07:05 UTC by sayooj006

Add support for DMA.
To enable DMA add CONFIG_ATM_DMA=y in Configuration file

2024-09-18 21:04 UTC, hzarnani commented
@sayooj006, where did this .c file originally come from?  Seems to be a copy from bare metal?

2024-09-19 05:09 UTC, sayooj006 commented
@hzarnani , Yes the C file is from bare metal.

2024-09-19 18:33 UTC, hzarnani commented
@sayooj006, could you please provide more context for this pull request?  I'd like to add reviewers who might not have any context for why this is being done or what specific problem is being solved.

2024-09-19 21:04 UTC, dt-atmosic commented
For the ATM33 platform, the WSTK provides the dma driver implementation.  It should not be duplicated in this manner.

2024-09-19 21:07 UTC, dt-atmosic requested changes
This change should **NOT** be merged.

2024-09-19 21:07 UTC, dt-atmosic commented on ATM33xx-5/drivers/CMakeLists.txt
> +add_subdirectory(dma)
Must be kept in alphabetical order.

2024-09-19 21:07 UTC, dt-atmosic commented on ATM33xx-5/drivers/dma/CMakeLists.txt
> +zephyr_sources_ifdef(CONFIG_ATM_DMA dma.c)
For the ATM33 platform, this implementation is provided by the WSTK.  It should not be duplicated in this manner.

2025-05-06 11:39 UTC, closed without merging